### ISSUE TITLE
resilenter_caller Typo

### ISSUE THREAD

**Issue by whosifrago53** [glizzykingdreko/resilient_caller#2]
Porcodio non sai neanche come si chiama il tuo modulo.

`from resilenter_caller import resilient_call, RETRY_EVENT
`

`from resilienter_caller import resilient_call, RETRY_EVENT
`

**Comment by glizzykingdreko** [comment]
Hi whosifrago
The repository name was updated a few versions ago, so if you use the latest version you should change the import name.
If I forgot to update it in any examples, I ask for your forgiveness and ask you to point them out to me or directly push a commit
